### ISSUE TITLE
Windows MSVC compiler sometimes panics.

### ISSUE THREAD

**Issue by BobG1983** [smol-rs/fastrand#84]
Repro:

Clone https://www.github.com/BobG1983/rantz_random.git
run cargo test
run cargo test again.

Issue:

The compiler panics with the following output:

```
thread 'rustc' panicked at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db\compiler\rustc_data_structures\src\sync.rs:338:42:
assertion failed: *old == value
stack backtrace:
   0:     0x7ffe2a00d5d3 - std::backtrace_rs::backtrace::dbghelp64::trace
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1:     0x7ffe2a00d5d3 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ffe2a00d5d3 - std::backtrace::Backtrace::create
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\backtrace.rs:331
   3:     0x7ffe2a00d51a - std::backtrace::Backtrace::force_capture
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\backtrace.rs:312
   4:     0x7ffde674e510 - memchr
   5:     0x7ffe2a027337 - alloc::boxed::impl$50::call
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\alloc\src\boxed.rs:2076
   6:     0x7ffe2a027337 - std::panicking::rust_panic_with_hook
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\panicking.rs:801
   7:     0x7ffe2a02710f - std::panicking::begin_panic_handler::closure$0
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\panicking.rs:660
   8:     0x7ffe2a0245af - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\sys\backtrace.rs:171
   9:     0x7ffe2a026d66 - std::panicking::begin_panic_handler
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\panicking.rs:658
  10:     0x7ffe2a07cf64 - core::panicking::panic_fmt
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\core\src\panicking.rs:74
  11:     0x7ffe2a07d00d - core::panicking::panic
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\core\src\panicking.rs:148
  12:     0x7ffde51a4443 - <rustc_middle[3720665636316a56]::ty::context::TyCtxt>::set_alloc_id_same_memory
  13:     0x7ffde507a807 - <rustc_metadata[beec48ef7521b97d]::rmeta::decoder::DecodeContext as rustc_type_ir[69993b1d9e925772]::codec::TyDecoder>::decode_alloc_id
  14:     0x7ffde6247d9b - <aho_corasick[ac69cc43042af094]::util::prefilter::Builder>::build
  15:     0x7ffde6232446 - <aho_corasick[ac69cc43042af094]::util::prefilter::Builder>::build
  16:     0x7ffde62cdfc3 - <rustc_metadata[beec48ef7521b97d]::creader::alloc_error_handler_spans::Finder as rustc_ast[9ac2f267a929ff38]::visit::Visitor>::visit_item
  17:     0x7ffde5d3de6b - rustc_query_impl[f350898e45c5ba56]::plumbing::query_key_hash_verify_all
  18:     0x7ffde5c3453e - rustc_ty_utils[4ce48a55c0187f78]::ty::self_ty_of_trait_impl_enabling_order_dep_trait_object_hack
  19:     0x7ffde4e95ad5 - rustc_query_impl[f350898e45c5ba56]::query_system
  20:     0x7ffde661731f - <rustc_middle[3720665636316a56]::ty::context::TyCtxt>::instance_mir
  21:     0x7ffde61d8ab3 - rustc_monomorphize[cd4d3c758268f64]::is_call_from_compiler_builtins_to_upstream_monomorphization
  22:     0x7ffde61d5bc9 - rustc_monomorphize[cd4d3c758268f64]::is_call_from_compiler_builtins_to_upstream_monomorphization
  23:     0x7ffde61d7872 - rustc_monomorphize[cd4d3c758268f64]::is_call_from_compiler_builtins_to_upstream_monomorphization
  24:     0x7ffde76ebb5d - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  25:     0x7ffde76f0727 - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  26:     0x7ffde76ebe18 - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  27:     0x7ffde76f0727 - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  28:     0x7ffde76ebe18 - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  29:     0x7ffde76f0727 - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  30:     0x7ffde76ebe18 - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  31:     0x7ffde76f5a57 - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  32:     0x7ffde7db1669 - <rayon_core[744fdfe6ee7fdbd]::registry::WorkerThread>::wait_until_cold
  33:     0x7ffde7dadc35 - <rayon_core[744fdfe6ee7fdbd]::registry::ThreadBuilder>::run
  34:     0x7ffde67514dc - memchr
  35:     0x7ffde6745efd - memchr
  36:     0x7ffde6750dd1 - memchr
  37:     0x7ffe2a03834d - alloc::boxed::impl$48::call_once
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\alloc\src\boxed.rs:2062
  38:     0x7ffe2a03834d - alloc::boxed::impl$48::call_once
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\alloc\src\boxed.rs:2062
  39:     0x7ffe2a03834d - std::sys::pal::windows::thread::impl$0::new::thread_start
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\sys\pal\windows\thread.rs:52
  40:     0x7ffeb94c257d - BaseThreadInitThunk
  41:     0x7ffeba70af28 - RtlUserThreadStart


rustc version: 1.81.0-nightly (59e2c01c2 2024-06-17)
platform: x86_64-pc-windows-msvc

query stack during panic:
#0 [optimized_mir] optimizing MIR for `fastrand::global_rng::u128`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
thread 'rustc' panicked at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db\compiler\rustc_data_structures\src\sync.rs:338:42:
assertion failed: *old == value
stack backtrace:
   0:     0x7ffe2a00d5d3 - std::backtrace_rs::backtrace::dbghelp64::trace
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1:     0x7ffe2a00d5d3 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ffe2a00d5d3 - std::backtrace::Backtrace::create
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\backtrace.rs:331
   3:     0x7ffe2a00d51a - std::backtrace::Backtrace::force_capture
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\backtrace.rs:312
   4:     0x7ffde674e510 - memchr
   5:     0x7ffe2a027337 - alloc::boxed::impl$50::call
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\alloc\src\boxed.rs:2076
   6:     0x7ffe2a027337 - std::panicking::rust_panic_with_hook
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\panicking.rs:801
   7:     0x7ffe2a02710f - std::panicking::begin_panic_handler::closure$0
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\panicking.rs:660
   8:     0x7ffe2a0245af - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\sys\backtrace.rs:171
   9:     0x7ffe2a026d66 - std::panicking::begin_panic_handler
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\panicking.rs:658
  10:     0x7ffe2a07cf64 - core::panicking::panic_fmt
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\core\src\panicking.rs:74
  11:     0x7ffe2a07d00d - core::panicking::panic
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\core\src\panicking.rs:148
  12:     0x7ffde51a4443 - <rustc_middle[3720665636316a56]::ty::context::TyCtxt>::set_alloc_id_same_memory
  13:     0x7ffde507a807 - <rustc_metadata[beec48ef7521b97d]::rmeta::decoder::DecodeContext as rustc_type_ir[69993b1d9e925772]::codec::TyDecoder>::decode_alloc_id
  14:     0x7ffde6247d9b - <aho_corasick[ac69cc43042af094]::util::prefilter::Builder>::build
  15:     0x7ffde6232446 - <aho_corasick[ac69cc43042af094]::util::prefilter::Builder>::build
  16:     0x7ffde62cdfc3 - <rustc_metadata[beec48ef7521b97d]::creader::alloc_error_handler_spans::Finder as rustc_ast[9ac2f267a929ff38]::visit::Visitor>::visit_item
  17:     0x7ffde5d3de6b - rustc_query_impl[f350898e45c5ba56]::plumbing::query_key_hash_verify_all
  18:     0x7ffde5c3453e - rustc_ty_utils[4ce48a55c0187f78]::ty::self_ty_of_trait_impl_enabling_order_dep_trait_object_hack
  19:     0x7ffde4e95ad5 - rustc_query_impl[f350898e45c5ba56]::query_system
  20:     0x7ffde661731f - <rustc_middle[3720665636316a56]::ty::context::TyCtxt>::instance_mir
  21:     0x7ffde61d8ab3 - rustc_monomorphize[cd4d3c758268f64]::is_call_from_compiler_builtins_to_upstream_monomorphization
  22:     0x7ffde61d5bc9 - rustc_monomorphize[cd4d3c758268f64]::is_call_from_compiler_builtins_to_upstream_monomorphization
  23:     0x7ffde61d7872 - rustc_monomorphize[cd4d3c758268f64]::is_call_from_compiler_builtins_to_upstream_monomorphization
  24:     0x7ffde76ebb5d - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  25:     0x7ffde76f0727 - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  26:     0x7ffde76ebe18 - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  27:     0x7ffde76f0727 - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  28:     0x7ffde76ebe18 - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  29:     0x7ffde76f5a57 - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  30:     0x7ffde7db1669 - <rayon_core[744fdfe6ee7fdbd]::registry::WorkerThread>::wait_until_cold
  31:     0x7ffde7dadc35 - <rayon_core[744fdfe6ee7fdbd]::registry::ThreadBuilder>::run
  32:     0x7ffde67514dc - memchr
  33:     0x7ffde6745efd - memchr
  34:     0x7ffde6750dd1 - memchr
  35:     0x7ffe2a03834d - alloc::boxed::impl$48::call_once
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\alloc\src\boxed.rs:2062
  36:     0x7ffe2a03834d - alloc::boxed::impl$48::call_once
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\alloc\src\boxed.rs:2062
  37:     0x7ffe2a03834d - std::sys::pal::windows::thread::impl$0::new::thread_start
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\sys\pal\windows\thread.rs:52
  38:     0x7ffeb94c257d - BaseThreadInitThunk
  39:     0x7ffeba70af28 - RtlUserThreadStart


query stack during panic:
#0 [optimized_mir] optimizing MIR for `fastrand::global_rng::i64`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
thread 'rustc' panicked at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db\compiler\rustc_data_structures\src\sync.rs:338:42:
assertion failed: *old == value
stack backtrace:
   0:     0x7ffe2a00d5d3 - std::backtrace_rs::backtrace::dbghelp64::trace
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1:     0x7ffe2a00d5d3 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ffe2a00d5d3 - std::backtrace::Backtrace::create
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\backtrace.rs:331
   3:     0x7ffe2a00d51a - std::backtrace::Backtrace::force_capture
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\backtrace.rs:312
   4:     0x7ffde674e510 - memchr
   5:     0x7ffe2a027337 - alloc::boxed::impl$50::call
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\alloc\src\boxed.rs:2076
   6:     0x7ffe2a027337 - std::panicking::rust_panic_with_hook
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\panicking.rs:801
   7:     0x7ffe2a02710f - std::panicking::begin_panic_handler::closure$0
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\panicking.rs:660
   8:     0x7ffe2a0245af - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\sys\backtrace.rs:171
   9:     0x7ffe2a026d66 - std::panicking::begin_panic_handler
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\panicking.rs:658
  10:     0x7ffe2a07cf64 - core::panicking::panic_fmt
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\core\src\panicking.rs:74
  11:     0x7ffe2a07d00d - core::panicking::panic
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\core\src\panicking.rs:148
  12:     0x7ffde51a4443 - <rustc_middle[3720665636316a56]::ty::context::TyCtxt>::set_alloc_id_same_memory
  13:     0x7ffde507a807 - <rustc_metadata[beec48ef7521b97d]::rmeta::decoder::DecodeContext as rustc_type_ir[69993b1d9e925772]::codec::TyDecoder>::decode_alloc_id
  14:     0x7ffde6247d9b - <aho_corasick[ac69cc43042af094]::util::prefilter::Builder>::build
  15:     0x7ffde6232446 - <aho_corasick[ac69cc43042af094]::util::prefilter::Builder>::build
  16:     0x7ffde62cdfc3 - <rustc_metadata[beec48ef7521b97d]::creader::alloc_error_handler_spans::Finder as rustc_ast[9ac2f267a929ff38]::visit::Visitor>::visit_item
  17:     0x7ffde5d3de6b - rustc_query_impl[f350898e45c5ba56]::plumbing::query_key_hash_verify_all
  18:     0x7ffde5c3453e - rustc_ty_utils[4ce48a55c0187f78]::ty::self_ty_of_trait_impl_enabling_order_dep_trait_object_hack
  19:     0x7ffde4e95ad5 - rustc_query_impl[f350898e45c5ba56]::query_system
  20:     0x7ffde661731f - <rustc_middle[3720665636316a56]::ty::context::TyCtxt>::instance_mir
  21:     0x7ffde61d8ab3 - rustc_monomorphize[cd4d3c758268f64]::is_call_from_compiler_builtins_to_upstream_monomorphization
  22:     0x7ffde61d5bc9 - rustc_monomorphize[cd4d3c758268f64]::is_call_from_compiler_builtins_to_upstream_monomorphization
  23:     0x7ffde61d7872 - rustc_monomorphize[cd4d3c758268f64]::is_call_from_compiler_builtins_to_upstream_monomorphization
  24:     0x7ffde76ebb5d - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  25:     0x7ffde76f0814 - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  26:     0x7ffde76ebe18 - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  27:     0x7ffde76f0727 - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  28:     0x7ffde76ebe18 - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  29:     0x7ffde76f5a57 - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  30:     0x7ffde7db1669 - <rayon_core[744fdfe6ee7fdbd]::registry::WorkerThread>::wait_until_cold
  31:     0x7ffde7dadc35 - <rayon_core[744fdfe6ee7fdbd]::registry::ThreadBuilder>::run
  32:     0x7ffde67514dc - memchr
  33:     0x7ffde6745efd - memchr
  34:     0x7ffde6750dd1 - memchr
  35:     0x7ffe2a03834d - alloc::boxed::impl$48::call_once
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\alloc\src\boxed.rs:2062
  36:     0x7ffe2a03834d - alloc::boxed::impl$48::call_once
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\alloc\src\boxed.rs:2062
  37:     0x7ffe2a03834d - std::sys::pal::windows::thread::impl$0::new::thread_start
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\sys\pal\windows\thread.rs:52
  38:     0x7ffeb94c257d - BaseThreadInitThunk
  39:     0x7ffeba70af28 - RtlUserThreadStart


query stack during panic:
#0 [optimized_mir] optimizing MIR for `fastrand::global_rng::i8`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
thread 'rustc' panicked at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db\compiler\rustc_data_structures\src\sync.rs:338:42:
assertion failed: *old == value
stack backtrace:
   0:     0x7ffe2a00d5d3 - std::backtrace_rs::backtrace::dbghelp64::trace
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1:     0x7ffe2a00d5d3 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ffe2a00d5d3 - std::backtrace::Backtrace::create
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\backtrace.rs:331
   3:     0x7ffe2a00d51a - std::backtrace::Backtrace::force_capture
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\backtrace.rs:312
   4:     0x7ffde674e510 - memchr
   5:     0x7ffe2a027337 - alloc::boxed::impl$50::call
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\alloc\src\boxed.rs:2076
   6:     0x7ffe2a027337 - std::panicking::rust_panic_with_hook
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\panicking.rs:801
   7:     0x7ffe2a02710f - std::panicking::begin_panic_handler::closure$0
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\panicking.rs:660
   8:     0x7ffe2a0245af - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\sys\backtrace.rs:171
   9:     0x7ffe2a026d66 - std::panicking::begin_panic_handler
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\panicking.rs:658
  10:     0x7ffe2a07cf64 - core::panicking::panic_fmt
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\core\src\panicking.rs:74
  11:     0x7ffe2a07d00d - core::panicking::panic
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\core\src\panicking.rs:148
  12:     0x7ffde51a4443 - <rustc_middle[3720665636316a56]::ty::context::TyCtxt>::set_alloc_id_same_memory
  13:     0x7ffde507a807 - <rustc_metadata[beec48ef7521b97d]::rmeta::decoder::DecodeContext as rustc_type_ir[69993b1d9e925772]::codec::TyDecoder>::decode_alloc_id
  14:     0x7ffde6247d9b - <aho_corasick[ac69cc43042af094]::util::prefilter::Builder>::build
  15:     0x7ffde6232446 - <aho_corasick[ac69cc43042af094]::util::prefilter::Builder>::build
  16:     0x7ffde62cdfc3 - <rustc_metadata[beec48ef7521b97d]::creader::alloc_error_handler_spans::Finder as rustc_ast[9ac2f267a929ff38]::visit::Visitor>::visit_item
  17:     0x7ffde5d3de6b - rustc_query_impl[f350898e45c5ba56]::plumbing::query_key_hash_verify_all
  18:     0x7ffde5c3453e - rustc_ty_utils[4ce48a55c0187f78]::ty::self_ty_of_trait_impl_enabling_order_dep_trait_object_hack
  19:     0x7ffde4e95ad5 - rustc_query_impl[f350898e45c5ba56]::query_system
  20:     0x7ffde661731f - <rustc_middle[3720665636316a56]::ty::context::TyCtxt>::instance_mir
  21:     0x7ffde61d8ab3 - rustc_monomorphize[cd4d3c758268f64]::is_call_from_compiler_builtins_to_upstream_monomorphization
  22:     0x7ffde61d5bc9 - rustc_monomorphize[cd4d3c758268f64]::is_call_from_compiler_builtins_to_upstream_monomorphization
  23:     0x7ffde61d7872 - rustc_monomorphize[cd4d3c758268f64]::is_call_from_compiler_builtins_to_upstream_monomorphization
  24:     0x7ffde76ebb5d - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  25:     0x7ffde76f0727 - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  26:     0x7ffde76ebe18 - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  27:     0x7ffde76f5a57 - <gimli[87f9d3ffa14e46ff]::write::str::LineStringTable>::get
  28:     0x7ffde7db1669 - <rayon_core[744fdfe6ee7fdbd]::registry::WorkerThread>::wait_until_cold
  29:     0x7ffde7dadc35 - <rayon_core[744fdfe6ee7fdbd]::registry::ThreadBuilder>::run
  30:     0x7ffde67514dc - memchr
  31:     0x7ffde6745efd - memchr
  32:     0x7ffde6750dd1 - memchr
  33:     0x7ffe2a03834d - alloc::boxed::impl$48::call_once
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\alloc\src\boxed.rs:2062
  34:     0x7ffe2a03834d - alloc::boxed::impl$48::call_once
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\alloc\src\boxed.rs:2062
  35:     0x7ffe2a03834d - std::sys::pal::windows::thread::impl$0::new::thread_start
                               at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library\std\src\sys\pal\windows\thread.rs:52
  36:     0x7ffeb94c257d - BaseThreadInitThunk
  37:     0x7ffeba70af28 - RtlUserThreadStart


query stack during panic:
#0 [optimized_mir] optimizing MIR for `fastrand::global_rng::i16`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
```

**Comment by notgull** [comment]
What compiler versions is this observed with? This is more likely a compiler bug, since it works fine in other targets for Rustc.

**Comment by BobG1983** [comment]
Nightly from yesterday.

**Comment by taiki-e** [comment]
"Compiler panic" is always a compiler bug. Please open the issue as "Internal Compiler Error" at https://github.com/rust-lang/rust.
